<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <div class="newproducts">
        <div class="carousel">
            <div class="slider">
                <?php $i=0; foreach ($_products->getItems() as $_product): $i++; ?>
                    <div class="item slide <?php if(($i == 4 && $_products->getSize() < 5) || ($i == $_products->getSize()) ) echo 'last'?>"> 
                        <?php include('view/labels.phtml')  ?>    
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        
<div class="box-product-item">
<div class="view-first">
<div class="view-content">
<div class="image">
<a href="<?php echo $_product->getProductUrl() ?>">
<img alt="<?php echo $this->htmlEscape($_product->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(188,204) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>"">
</a>
</div>
<div class="name">
<?php

 $shortenby = themeOptions('shorten_name');

 $product_name = $this->htmlEscape($_product->getName());
 
 if(strlen($product_name) > $shortenby) { $product_name = substr($product_name,0,$shortenby).'...'; }
?>
<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $product_name ?></a>
</div>
<div class="price">
    
<?php
 if($_product->getSpecialPrice() != ''){// has special price
        
    echo '<span class="price-old">'.strip_tags(Mage::helper('core')->currency($_product->getPrice())).'</span><span class="price-new">'.strip_tags(Mage::helper('core')->currency($_product->getSpecialPrice())).'</span>';
 }
 else
 {
    echo strip_tags(Mage::helper('core')->currency($_product->getPrice()));
    
 }
?>    
    
    </div>
</div>
<div class="box-product-buttons">
<div class="buttons-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"></div>
<div class="buttons-wish" onclick="setLocation('<?php echo $this->getAddToWishlistUrl($_product) ?>')"></div>
<div class="buttons-compare" onclick="setLocation('<?php echo $this->getAddToCompareUrl($_product) ?>')"></div>
<div class="buttons-more" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"></div>
<div class="buttons-cart-text" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart') ?></div>        
</div>
</div>
</div>
                      
                    </div>
                <?php endforeach; ?>
            </div>             
        </div>
        <?php if($_products->getSize() > 1): ?>
            <div class="prev new-arrow">&nbsp;</div>
            <div class="next new-arrow">&nbsp;</div>  
        <?php endif; ?>
    </div>     
    <div class="clear"></div>
    <?php if($_products->getSize() > 1): ?>
        <script type="text/javascript">
            jQuery('.new-arrow.prev').addClass('disabled');
            jQuery('.carousel').iosSlider({
                desktopClickDrag: true,
                snapToChildren: true,
                infiniteSlider: false,
                navNextSelector: '.new-arrow.next',
                navPrevSelector: '.new-arrow.prev',
                lastSlideOffset: 3,
                onFirstSlideComplete: function(){
                    jQuery('.new-arrow.prev').addClass('disabled');
                },
                onLastSlideComplete: function(){
                    jQuery('.new-arrow.next').addClass('disabled');
                },
                onSlideChange: function(){
                    jQuery('.new-arrow.prev').removeClass('disabled');
                    jQuery('.new-arrow.next').removeClass('disabled');
                }
            });               
        </script>    
    <?php endif; ?>
<?php endif; ?>