
<div id="top"></div>

<div id="header_menu">
    <?php echo $this->getChildHtml('topLinks') ?>  <?php echo $this->getChildHtml('currency') ?>
</div>
<div class="header-container">
    <div class="header">
        <div class="header-left">
            <div class="welcome-msg"><?php echo $this->getWelcome() ?></div>
            <?php echo $this->getChildHtml('store_language') ?>        
            <?php if ($this->getIsHomePage()):?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php else:?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php endif?>
            
        </div>
        <div id="phone"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('header_working_time')->toHtml(); ?></div>
        <div class="header-center">
            
            <?php echo $this->getChildHtml('topBar') ?>   
        </div>        
        <div class="header-right">
            
            <div class="minicart-wrapper">
                <div class="icon" onclick="location.href='<?php echo $this->getUrl('checkout/cart')?>'"></div>
                <div class="minicart">
                    
                    <?php echo $this->getChildHtml('top_cart') ?>
                    
                </div>
                
            </div>
            <div class="clear"></div>   
            
        </div>      
    </div>
    <?php echo $this->getChildHtml('topMenu') ?>
    <?php echo $this->getChildHtml('topBread') ?>
    <?php echo $this->getChildHtml('topContainer'); ?>

</div>