<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
<script type="text/javascript">var slide_on=false;</script>
<?php 
function themeOptions ($themeOption) {
	switch ($themeOption) {
     
     /* GENERAL */
     
     case 'additionalLink':
	   return Mage::getStoreConfig('mygeneral/generaloptions/additional_nav', Mage::app()->getStore()->getId());
	 break;
     case 'menutype':
       return Mage::getStoreConfig('mygeneral/generaloptions/menutype', Mage::app()->getStore()->getId());
	 break;
	 case 'googlefont':
	   return Mage::getStoreConfig('mygeneral/generaloptions/googlefont', Mage::app()->getStore()->getId());
	 break; 
     case 'topbanner':
	   return Mage::getStoreConfig('mygeneral/generaloptions/topbanner', Mage::app()->getStore()->getId());
	 break;     
     case 'phones':
	   return Mage::getStoreConfig('mygeneral/generaloptions/phones', Mage::app()->getStore()->getId());
	 break;
     case 'additionalLinkUrl':
	   return Mage::getStoreConfig('mygeneral/generaloptions/additional_nav_href', Mage::app()->getStore()->getId());
	 break;
     case 'topbtn':
	   return (Mage::getStoreConfig('mygeneral/generaloptions/topbtn', Mage::app()->getStore()->getId()) == 1);
	 break;
     case 'enable_ajax':
       return (Mage::getStoreConfig('mygeneral/generaloptions/enable_ajax', Mage::app()->getStore()->getId()) == 1);
     break;
     case 'hide_wish':
       return (Mage::getStoreConfig('mygeneral/generaloptions/hide_wish', Mage::app()->getStore()->getId()) == 1);
     break;
     case 'hide_compare':
       return (Mage::getStoreConfig('mygeneral/generaloptions/hide_compare', Mage::app()->getStore()->getId()) == 1);
     break;
     case 'hide_cart':
       return (Mage::getStoreConfig('mygeneral/generaloptions/hide_cart', Mage::app()->getStore()->getId()) == 1);
     break;
     case 'hide_more':
       return (Mage::getStoreConfig('mygeneral/generaloptions/hide_more', Mage::app()->getStore()->getId()) == 1);
     break;
     case 'big_addtocart':
       return (Mage::getStoreConfig('mygeneral/generaloptions/big_addtocart', Mage::app()->getStore()->getId()) == 1);
     break;

      /* Background */
     
     case 'pattern':
	   return Mage::getStoreConfig('mygeneral/background/pattern', Mage::app()->getStore()->getId());
	 break; 
     case 'maincolor':
	   return Mage::getStoreConfig('mygeneral/background/maincolor', Mage::app()->getStore()->getId());
	 break;  
     case 'bg_repeat':
	   return Mage::getStoreConfig('mygeneral/background/bg_repeat', Mage::app()->getStore()->getId());
	 break;  
     case 'bg_attachment':
	   return Mage::getStoreConfig('mygeneral/background/bg_attachment', Mage::app()->getStore()->getId());
	 break;  
     case 'bg_position_x':
	   return Mage::getStoreConfig('mygeneral/background/bg_position_x', Mage::app()->getStore()->getId());
	 break; 
     case 'bg_position_y':
	   return Mage::getStoreConfig('mygeneral/background/bg_position_y', Mage::app()->getStore()->getId());
	 break;   
     
     /* SLIDESHOW */
     
     case 'use_slideshow':
	   return (Mage::getStoreConfig('mygeneral/slideshow/use_slideshow', Mage::app()->getStore()->getId()) == 1);
	 break;
     case 'autoplay':
	   return (Mage::getStoreConfig('mygeneral/slideshow/autoplay', Mage::app()->getStore()->getId()) == 1);
	 break;
     case 'speed':
	   return Mage::getStoreConfig('mygeneral/slideshow/speed', Mage::app()->getStore()->getId());
	 break;
     
     /* PRODUCT LIST */
     
     case 'shorten_name':
       return Mage::getStoreConfig('mygeneral/product_list/shorten_name', Mage::app()->getStore()->getId());
	 break;
     
     case 'layer':
       return Mage::getStoreConfig('mygeneral/product_list/layer', Mage::app()->getStore()->getId());
	 break;
     case 'new_label':
       return (Mage::getStoreConfig('mygeneral/product_list/new_label', Mage::app()->getStore()->getId()) == 1);
	 break;
     case 'sale_label':
       return (Mage::getStoreConfig('mygeneral/product_list/sale_label', Mage::app()->getStore()->getId()) == 1);
	 break;
    
     /* SHARE */
     case 'facebookgroupid':
	   return Mage::getStoreConfig('mygeneral/share/facebookgroupid', Mage::app()->getStore()->getId());
	 break;
	/* SHARE */
     case 'twittername':
	   return Mage::getStoreConfig('mygeneral/share/twittername', Mage::app()->getStore()->getId());
	 break;
     case 'use_share':
	   return (Mage::getStoreConfig('mygeneral/share/use_share', Mage::app()->getStore()->getId()) == 1);
	 break;
     case 'share_code':
	   return Mage::getStoreConfig('mygeneral/share/share_code', Mage::app()->getStore()->getId());
	 break;
     
     /* PRODUCT PAGE */
     
     case 'use_zoom':
	   return (Mage::getStoreConfig('mygeneral/productpage/use_zoom', Mage::app()->getStore()->getId()) == 1);
	 break;
     case 'use_carousel':
	   return (Mage::getStoreConfig('mygeneral/productpage/use_carousel', Mage::app()->getStore()->getId()) == 1);
	 break;
     
     
     /* COLORS */
     
     case 'active_color':
	   return Mage::getStoreConfig('mygeneral/colors/active_color');
	 break;
     case 'button_hover':
	   return Mage::getStoreConfig('mygeneral/colors/button_hover');
	 break;
     
	}
}
?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link href='//fonts.googleapis.com/css?family=<?php echo themeOptions('googlefont'); ?>&subset=latin' rel='stylesheet' type='text/css'>
<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "fdf72e22-4d1c-4270-9aea-a784ad6c30c2"});</script>
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<script type="text/javascript">
  var BASE_URL = '<?php echo $this->getBaseUrl(); ?>';
  var clearenceUrl = '<?php echo themeOptions('additionalLinkUrl'); ?>';
</script>
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>

<!-- BEAUTYSHOP MENU -->
<?php $menutype = themeOptions('menutype'); ?>
<?php if($menutype == 1): ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/menu1.css'); ?>" media="screen"/>
<?php elseif($menutype == 2): ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/menu2.css'); ?>" media="screen"/>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('varien/menu.js'); ?>"></script>
<?php endif; ?>

<!-- BEAUTYSHOP ZOOM -->
<?php $use_zoom = themeOptions('use_zoom'); ?>
<?php if($use_zoom): ?>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('zoom/easyzoom.js'); ?>"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/easyzoom.css'); ?>" media="screen"/>
<?php endif; ?>


<?php $use_slideshow = themeOptions('use_slideshow'); ?>


<?php 
$selectors = Array();
$selectors['button_color_bg'] = '.box-product-buttons, .block-cart-header .button-show, .box-product-buttons div, .newproduct_grid, button.button, .product-view .product-img-box .main-image .lightbox-btn a, .product-list .product-list-buttons .pbuttons .img, .quantity_box_button_down:hover, .quantity_box_button_up:hover, .product-list .product-list-buttons .pbuttons:hover, .view-mode strong.grid, .pager .view-mode a.grid 
';

$selectors['active_color_bg'] = '.header .icon, .iosSlider .sliderNavi .naviItem.selected, .box-product-item .name a, .box-product-buttons div:hover, button.button:hover, .product-list .product-list-buttons .pbuttons .img2, .product-view .product-img-box .main-image .lightbox-btn a:hover, .view-mode strong.grid, .view-mode strong.list, .pager .view-mode a:hover, .prev:hover, .next:hover, #message a:hover
';

$selectors['active_color_text'] = '#footer h3, .box-product-item .price, a, .special-price .price-label, #phone strong, #phone b, #nav .level1 > a > span';

$selectors['active_color_border'] = '#nav > li.over, #nav > li:hover, #nav > li.active, #nav > li > ul > li ul > li a:hover';

    function jsString($str='') { 
        return trim(preg_replace("/('|\"|\r?\n)/", '', $str)); 
    }     
?>


<style type="text/css">
    /* Colors */
    <?php echo jsString($selectors['button_color_bg']); ?>              { background-color: #<?php echo themeOptions('active_color') ?>!important; }
    
    <?php echo jsString($selectors['active_color_bg']); ?>          { background-color: #<?php echo themeOptions('button_hover') ?>!important; }
    
    <?php echo jsString($selectors['active_color_text']); ?>          { color: #<?php echo themeOptions('button_hover') ?>; } 

    <?php echo jsString($selectors['active_color_border']); ?>          { border-bottom-color: #<?php echo themeOptions('button_hover') ?>!important; } 
</style>

<?php if($use_slideshow): ?>
<?php $speed = themeOptions('speed'); ?>
<script type="text/javascript">
    if(slide_on){
        jQuery(document).ready(function($) {
            $('.iosSlider').iosSlider({
                desktopClickDrag: true,
                touchMoveThreshold:4,
                snapToChildren: true,
                infiniteSlider: true,
                autoSlide:<?php echo (themeOptions('autoplay')) ? 'true' : 'false'; ?>,
                autoSlideTimer:<?php echo ($speed) ? $speed : '3000'  ?>,
        		navSlideSelector: '.sliderNavi .naviItem',                
                navNextSelector: '.iosSlider .next',
                navPrevSelector: '.iosSlider .prev',
        		onSlideChange: slideContentChange,
        		onSlideComplete: slideContentComplete,
        		onSliderLoaded: slideContentLoaded
            }); 
                       	
        }); 
    }
</script>
<?php endif; ?>


<script type="text/javascript"><!--

jQuery(document).ready(function() {
      
      // Image animation
      jQuery(".fade-image").live({
        mouseenter:
           function()
           {
				jQuery(this).stop().fadeTo(300, 0.6);
           },
        mouseleave:
           function()
           {
				jQuery(this).stop().fadeTo(300, 1);
           }
       }
    );
      
   
});

--></script>

<style>
	body{
	    background-color:#<?php echo themeOptions('maincolor') ?>;
	    background-attachment: <?php echo themeOptions('bg_attachment') ?>;
	    background-position: <?php echo themeOptions('bg_position_y') ?> <?php echo themeOptions('bg_position_x') ?>;
	    background-repeat: <?php echo themeOptions('bg_repeat') ?>;
	}  
	
	.buttons-cart-text, .box-product-item .name a, .box-product-item .price, h1, h2, button.button, .block .block-title strong span, #narrow-by-list dt, .block-cart-header .btn-checkout span, .form-subscribe-header h4, .product-view .product-shop .price-box .price, .price-box .price  {
		font-family: <?php 
		  $googlefont_name = explode(":", themeOptions('googlefont'));
		  $googlefont_name = $googlefont_name[0];
		  
		  echo $googlefont_name;
		 ?>;
	}
	<?php if(themeOptions('hide_wish')): ?>
	   
		.buttons-wish, #header_menu .links li:nth-child(2) {
			display:none;
		}
		.buttons-more {
			border-right: 1px solid #EAE5E4;
		}
	<?php endif; ?>
	<?php if(themeOptions('hide_compare')): ?>
	   
		.buttons-compare {
			display:none;
		}
		.buttons-more {
			border-right: 1px solid #EAE5E4;
		}
	<?php endif; ?>
	<?php if(themeOptions('hide_more')): ?>
	   
		.buttons-more {
			display:none;
		}
		
	<?php endif; ?>
	<?php if(themeOptions('hide_cart')): ?>
	   
		.buttons-cart, .btn-cart, .minicart-wrapper, .top-link-cart-li, .add-to-box {
			display:none!important;
		}
	   
	<?php endif; ?>
	<?php if(themeOptions('big_addtocart')): ?>
	   
		.buttons-more, .buttons-compare, .buttons-wish {
			display:none!important;
		}
		
		.buttons-cart-text {
			display:inline;
		}
	<?php endif; ?>
	
	<?php if((themeOptions('hide_cart'))&&(themeOptions('hide_more'))&&(themeOptions('hide_compare'))&&(themeOptions('hide_wish'))): ?>
	   
		.box-product-buttons {
			display:none;
		}
	   
	<?php endif; ?>
	
</style>
<?php if(themeOptions('pattern') && themeOptions('pattern') != ''): ?>
    <style>
        body{ background-image: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'wysiwyg/beautyshop/'.themeOptions('pattern') ?>); }    
    </style>
<?php endif; ?>
<!--[if IE 7]>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/ie7.css'); ?>" media="screen"/>
<![endif]-->
<!--[if IE 9]>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/ie9.css'); ?>" media="screen"/>
<![endif]-->